{% set version = "0.5.6" %}

package:
  name: bmi-tester
  version: {{ version }}

source:
  url: https://github.com/csdms/bmi-tester/archive/v{{ version }}.tar.gz
  sha256: 2988c112c376a4fff50fec2c043090ce144f10123876cb3c60d04f7070714fa0

build:
  number: 0
  entry_points:
    - bmi-test=bmi_tester.bmipytest:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py2k]


requirements:
  host:
    - python
    - pip
    - numpy
    - gimli.units
  run:
    - python
    - numpy
    - pytest
    - pytest-dependency
    - standard_names
    - model_metadata
    - click
    - gimli.units

test:
  imports:
    - bmi_tester
  commands:
    - bmi-test --help
    - bmi-test --version

about:
  home: http://github.com/csdms/bmi-tester
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Test Python model implementations of the Basic Model Interface
  description: |
    The bmi_tester package provides a command-line utility for
    testing Python classes that implement the Basic Model Interface
    (BMI). bmi_tester also provides a Python interface to the tester
    that allows users to run tests programmatically.
  doc_url: http://bmi-tester.readthedocs.io/en/latest/
  dev_url: http://github.com/csdms/bmi-tester

extra:
  recipe-maintainers:
    - mcflugen
    - mdpiper
