{% set version = "0.5.7" %}

package:
  name: bmi-tester
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bmi-tester/bmi_tester-0.5.7.tar.gz
  sha256: 97ae380f8ee2af6e7530db234c4b9503922177e50045229e6278b6894aa72a80

build:
  noarch: python
  number: 0
  entry_points:
    - bmi-test=bmi_tester.bmipytest:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv


requirements:
  host:
    - python >=3.10
    - pip
    - numpy
    - gimli.units
  run:
    - python >=3.10
    - numpy
    - pytest
    - pytest-dependency
    - standard_names
    - model_metadata
    - click
    - gimli.units

test:
  imports:
    - bmi_tester
  commands:
    - bmi-test --help
    - bmi-test --version

about:
  home: http://github.com/csdms/bmi-tester
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Test Python model implementations of the Basic Model Interface
  description: |
    The bmi_tester package provides a command-line utility for
    testing Python classes that implement the Basic Model Interface
    (BMI). bmi_tester also provides a Python interface to the tester
    that allows users to run tests programmatically.
  doc_url: http://bmi-tester.readthedocs.io/en/latest/
  dev_url: http://github.com/csdms/bmi-tester

extra:
  recipe-maintainers:
    - mcflugen
    - mdpiper
